### ISSUE TITLE
Reference to ResultTypes.jl

### ISSUE THREAD

**Issue by rofinn** [jakobnissen/ErrorTypes.jl#4]
Might be helpful to document how this package differs from [ResultTypes.jl](https://github.com/iamed2/ResultTypes.jl)? AFAICT, they're trying to solve the same problem, but the solution is implemented slightly differently? If your solution is faster maybe some benchmarks would help?

**Comment by jakobnissen** [comment]
There is a small section on that on the front page of the docs at the bottom. More detail can be found on the [package announcement](https://discourse.julialang.org/t/ann-errortypes-jl-rust-like-safe-errors-in-julia/53953)
